In [1]:
import numpy as np

In [5]:
# 2D arrays
arr2D = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr2D, arr2D.dtype)

# To print only 2 and 7
print(arr2D[0:2, 1:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] int64
[[2]
 [7]]


In [11]:
# 3D arrays
arr3D = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr3D)

# Print first row 
print(arr3D[:, 0, :])

# Manipulating 
# Changing a entire row value to 10
arr3D[:, 0, :] = 10
print(arr3D)

# Vectorization
print(arr3D ** 2)

# Broadcasting
print(arr3D + 5)
arr = np.array([1,2
print(

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[1 2 3]]
[[[10 10 10]
  [ 4  5  6]
  [ 7  8  9]]]
[[[100 100 100]
  [ 16  25  36]
  [ 49  64  81]]]
[[[15 15 15]
  [ 9 10 11]
  [12 13 14]]]
