In [1]:
import numpy as np

In [5]:
# 1. Reshaping -> Converting array
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_arr = arr.reshape((3,2))
print(reshaped_arr)

# Flattening array to 1D
flattened_arr = arr.flatten()
print(flattened_arr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [12]:
# 2. Indexing
# Normal indexing
print(arr[1,2])

# Fancy indexing
# Eg to print the elements of only certain indexes like 2,3,4,5
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 89])
indexes = [2,3,4,5]
print(arr2[indexes])

# Boolean indexing
print(arr2[arr2>3])
# To print all even numbers
print(arr2[arr2%2==0])

6
[3 4 5 6]
[ 4  5  6  7 89]
[2 4 6]


In [17]:
# 3. Slicing 
print(arr2[1:6])
print(arr2[3:])
print(arr[:5])

[2 3 4 5 6]
[ 4  5  6  7 89]
[[1 2 3]
 [4 5 6]]
