In [1]:
import numpy as np

In [16]:
# Creating numpy arrays
arr = np.array([1,2,3,4,5,6])
print(arr, type(arr))

# Creating array with scratch
# 1. With all zeros
arr = np.zeros((2,3))
print(arr)

# 2. With all ones
arr = np.ones((3,3))
print(arr)

# 3. Full with a value
arr = np.full((3,3), 22)
print(arr)

# 4. Create identity matrix
arr = np.eye(3)
print(arr)

# 5. With arange
arr = np.arange(1, 10, 2)
print(arr)

# 6. linspace -> To create evenly space array
arr = np.linspace(1,100,5)
print(arr)


[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[22 22 22]
 [22 22 22]
 [22 22 22]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  1.    25.75  50.5   75.25 100.  ]


In [21]:
# Numpy arrays properties
arr = np.array([[1,2,3], [4,5,6]])
# shape -> To print the dimension of array
print(arr.shape)

# size -> To get total elements of array
print(arr.size)

# dtype -> To print data type of array
print(arr.dtype)

# ndim -> To get the number of dimensions (axes)
print(arr.ndim)

# astype -> to convert type and create new array 
arr2 = arr.astype(np.int64)
print(arr2)




(2, 3)
6
int64
2
[[1 2 3]
 [4 5 6]]
